[2012-10-13 16:43:59] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /Library/WebServer/Documents/Symfony2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 92 [] []
[2012-11-23 17:36:46] request.INFO: Matched route "_survey" (parameters: "_controller": "TrainingCompany\QueryBundle\Controller\DefaultController::queryAction", "_route": "_survey") [] []
[2012-11-23 17:36:49] request.CRITICAL: Doctrine\DBAL\DBALException: An exception occurred while executing 'INSERT INTO q_comments (pid, qid, qno, comment) VALUES (?, ?, ?, ?)' with params {"1":1,"2":"GdwMiD8zdpFD8Ldm","3":1,"4":"Lorem Ipsum"}:

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'GdwMiD8zdpFD8Ldm' for column 'qid' at row 1 (uncaught exception) at /usr/htdocs/TrainingCompany/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 47 [] []
[2012-11-23 17:37:43] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-11-23 17:37:43] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest". [] []
[2012-11-23 17:37:43] request.INFO: Matched route "_survey" (parameters: "_controller": "TrainingCompany\QueryBundle\Controller\DefaultController::queryAction", "_route": "_survey") [] []
[2012-11-23 17:37:43] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest". [] []
[2012-11-23 17:37:43] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-11-23 17:37:43] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". [] []
[2012-11-23 17:37:43] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". [] []
[2012-11-23 17:37:43] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". [] []
[2012-11-23 17:37:44] doctrine.DEBUG: SELECT t0.id AS id1, t0.pid AS pid2, t0.qid AS qid3, t0.qno AS qno4, t0.answer AS answer5 FROM q_responses t0 WHERE t0.pid = ? AND t0.qid = ? AND t0.qno = ? LIMIT 1 [1,"GdwMiD8zdpFD8Ldm",1] []
[2012-11-23 17:37:45] doctrine.DEBUG: SELECT t0.id AS id1, t0.pid AS pid2, t0.qid AS qid3, t0.qno AS qno4, t0.comment AS comment5 FROM q_comments t0 WHERE t0.pid = ? AND t0.qid = ? AND t0.qno = ? LIMIT 1 [1,"GdwMiD8zdpFD8Ldm",1] []
[2012-11-23 17:37:46] doctrine.DEBUG: SELECT t0.id AS id1, t0.pid AS pid2, t0.qid AS qid3, t0.qno AS qno4, t0.answer AS answer5 FROM q_responses t0 WHERE t0.pid = ? AND t0.qid = ? AND t0.qno = ? LIMIT 1 [1,"GdwMiD8zdpFD8Ldm",1] []
[2012-11-23 17:37:46] doctrine.DEBUG: SELECT t0.id AS id1, t0.pid AS pid2, t0.qid AS qid3, t0.qno AS qno4, t0.comment AS comment5 FROM q_comments t0 WHERE t0.pid = ? AND t0.qid = ? AND t0.qno = ? LIMIT 1 [1,"GdwMiD8zdpFD8Ldm",1] []
[2012-11-23 17:37:47] doctrine.DEBUG: "START TRANSACTION" [] []
[2012-11-23 17:37:47] doctrine.DEBUG: INSERT INTO q_comments (pid, qid, qno, comment) VALUES (?, ?, ?, ?) {"1":1,"2":"GdwMiD8zdpFD8Ldm","3":1,"4":"Lorem Ipsum"} []
[2012-11-23 17:37:47] doctrine.DEBUG: "ROLLBACK" [] []
[2012-11-23 17:37:47] event.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException". [] []
[2012-11-23 17:37:47] request.CRITICAL: Doctrine\DBAL\DBALException: An exception occurred while executing 'INSERT INTO q_comments (pid, qid, qno, comment) VALUES (?, ?, ?, ?)' with params {"1":1,"2":"GdwMiD8zdpFD8Ldm","3":1,"4":"Lorem Ipsum"}:

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'GdwMiD8zdpFD8Ldm' for column 'qid' at row 1 (uncaught exception) at /usr/htdocs/TrainingCompany/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 47 [] []
[2012-11-23 17:37:47] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". [] []
[2012-11-23 17:37:47] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest". [] []
[2012-11-23 17:37:47] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest". [] []
[2012-11-23 17:37:47] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". [] []
[2012-11-23 17:37:47] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". [] []
[2012-11-23 17:37:47] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". [] []
[2012-11-23 17:37:47] event.DEBUG: Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". [] []
[2012-11-23 17:37:49] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse". [] []
[2012-11-23 17:37:49] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-11-23 17:37:49] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-11-23 17:37:49] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse". [] []
[2012-11-23 17:37:50] event.DEBUG: Listener "Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException" stopped propagation of the event "kernel.exception". [] []
[2012-11-23 17:37:50] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse". [] []
[2012-11-23 17:37:50] event.DEBUG: Notified event "kernel.response" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\CacheListener::onKernelResponse". [] []
[2012-11-23 17:37:50] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2012-11-23 17:37:50] event.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse". [] []
[2012-11-23 17:37:50] event.DEBUG: Notified event "kernel.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onKernelTerminate". [] []
